packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "*"
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: "*"
  "@sapphire/framework@*":
    dependencies:
      discord.js: "*"
  "@sapphire/plugin-logger@*":
    dependencies:
      "@sapphire/framework": "*"
      discord.js: "*"
enableGlobalCache: true
yarnPath: ".yarn/releases/yarn-berry.cjs"
